# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-03 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0002_loginattempts_useragents'),
        ('Questions', '0006_auto_20180225_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_answer', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('score', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SettingsExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_allow', models.DateTimeField()),
                ('end_allow', models.DateTimeField()),
                ('time', models.CharField(max_length=10)),
                ('attempts', models.IntegerField(default=1)),
                ('Layout', models.IntegerField(default=5)),
                ('Shuffle', models.BooleanField(default=True)),
                ('preview', models.BooleanField(default=False)),
                ('grade', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.SettingsExam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Question'),
        ),
        migrations.AddField(
            model_name='exam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.Client'),
        ),
    ]
