# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-03 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='settingsexam',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
