# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-04 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
        ('Exam', '0002_auto_20180303_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsexam',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Category.Category'),
            preserve_default=False,
        ),
    ]
