# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-23 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='file',
            new_name='active',
        ),
    ]
