# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-25 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_auto_20180223_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
