# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-27 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('password', models.CharField(blank=True, max_length=40, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('browser_family', models.CharField(blank=True, max_length=30, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=15, null=True)),
                ('os_family', models.CharField(blank=True, max_length=30, null=True)),
                ('os_version', models.CharField(blank=True, max_length=15, null=True)),
                ('device_family', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAgents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=25, null=True)),
                ('user', models.CharField(max_length=25)),
                ('browser_family', models.CharField(blank=True, max_length=30, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=15, null=True)),
                ('os_family', models.CharField(blank=True, max_length=30, null=True)),
                ('os_version', models.CharField(blank=True, max_length=15, null=True)),
                ('device_family', models.CharField(blank=True, max_length=30, null=True)),
                ('start_session', models.DateTimeField(auto_now_add=True)),
                ('end_session', models.DateTimeField(blank=True, null=True)),
                ('logout', models.BooleanField(default=False)),
            ],
        ),
    ]
