# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-20 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_auto_20180310_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='identity',
            field=models.CharField(default=11, max_length=30),
            preserve_default=False,
        ),
    ]
