# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-20 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_client_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
