# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-22 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0007_auto_20180722_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifyemail',
            name='email',
        ),
        migrations.AddField(
            model_name='verifyemail',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Client.Client'),
            preserve_default=False,
        ),
    ]
