# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-20 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_auto_20180622_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='identity',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
